### ISSUE TITLE
Lexical information

### ISSUE THREAD

**Issue by Hardmath123** [tjvr/moo#1]
Can we have tokens optionally store line/column number? This is useful for error messages, among other things.

**Comment by nanalan** [comment]
:+1: For this.
I'd use moo if it has line/col info.

**Comment by tjvr** [comment]
Okay @hardmath123. What do you think of 21921e3? :)

**Comment by bd82** [comment]
> Can we have tokens optionally store line/column number? This is useful for error messages, among other things.

* Sometimes the **offset** itself is also needed.
* Sometimes both the start and end versions of the lexical information are needed. I.E startOffset/endOffset.

**Comment by bd82** [comment]
> More seriously: this is a pain to do well. Unless I know that you have a specific newline rule, and none of your other rules can ever match a newline, then any of them could potentially match multiple newlines; I'd effectively have to do value.split('\n').length on every lex() call, which would kill performance.

From the main readme.md it seems like you wanted to avoid analyzing the regExp source.
But if you inspect the regExp patterns for those that **may** contain newlines you can only perform
newline processing only if those patterns (matching capturing group in the big regExp) is matched.

**Comment by Hardmath123** [comment]
> I was assuming you'd do line/col tracking yourself, in a trivial wrapper around lex().

See, this was my attitude when I made nearley, and look how much people complain about it! :P

Anyhow: getting the offset from the beginning of the string should be cheap, right? You just keep a running total of lengths of tokens. With that in mind, can we make line-number a function rather than a property? Calling `.linenumber()` on a token could compute its line number. Since the most common use-case for line numbers is error reporting, I think it's reasonable to generate a line number "on demand" for the offending token.

**Comment by tjvr** [comment]
I'll add offsets by default; that is indeed cheap.

> Calling .linenumber() on a token could compute its line number

That would be pretty expensive to compute; plus, I'd have to keep around all the prior tokens in order to do so.

Anyway, I've addressed this in 21921e3 by adding a separate `moo.lines()` mode, which wraps the core lexer, and special-cases the `\n` token. So I'm going to close this.

**Comment by Hardmath123** [comment]
Nice, thanks Tim.
