### ISSUE TITLE
Sorting mixed regex-and-string arrays by length is too magical

### ISSUE THREAD

**Issue by nathan** [tjvr/moo#13]
https://github.com/tjvr/moo/commit/0f74d78409001a06c99ec528c82746bb5ca7b75d#diff-ad6fc569c607df12db67c2b062111492L52

This *can* return the shorter match given `[/c0ffee?/, /[0-f\d]{3}/]` since `Array#sort` is [not guaranteed to be stable](https://tc39.github.io/ecma262/#sec-array.prototype.sort) and `compareByLength` is returning `NaN` anyway (which is [treated as `+0`](https://tc39.github.io/ecma262/#sec-sortcompare), equal).

**Comment by tjvr** [comment]
Ugh. I thought Array.sort was stable :(

What do you propose? Now we have `objectToArray` it seems entirely reasonable to pass a list of RegExps.

**Comment by nathan** [comment]
I *think* the least surprising thing to do is: filter out the regexes, sort the strings only, then append the regexes in the order they originally appeared. So the following:

```js
moo.compile({tok: [/t[ok]+/, /\w/, 'tok', 'token']})
```
Would match `/token|tok|t[ok]+|\w/`. That still seems a bit magical, though.

**Comment by tjvr** [comment]
> That still seems a bit magical, though

Right. But it's got to be less surprising than _requiring_ the user to pass all their literals in order of decreasing length!

**Comment by nathan** [comment]
Yes, you're probably right.
