### ISSUE TITLE
1-based line, 0-based column is inconsistent

### ISSUE THREAD

**Issue by nathan** [tjvr/moo#15]
I'm usually inclined to do everything in the code with 0 based indices and just add 1 when you want to display it to the user, but having line/column be 1-based could be okay too. The problem is that this is silly:

```js
throw new SyntaxError(`Expected value at ${file}:${t.lineno}:${t.column + 1}`)
```

**Comment by tjvr** [comment]
Agreed.

**Comment by nathan** [comment]
Guess we should wait on this until #14 is merged.

**Comment by tjvr** [comment]
Sorted :)
