### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by nanalan** [tjvr/moo#2]

**Comment by nanalan** [comment]
If we could somehow source [the package name](https://www.npmjs.com/package/moo) (that's totally empty at the minute), it'd be great.

**Comment by tjvr** [comment]
From the Readme:

> $ npm install moo, $ yarn install moo, or whatever will ship this code to your computer Hold up a second; we haven't published to NPM yet!

It may surprise you to learn I'm already in the process of doing that. :-)

**Comment by nanalan** [comment]
> From the Readme:
>> $ npm install moo, $ yarn install moo, or whatever will ship this code to your computer Hold up a second; we haven't published to NPM yet!
(That's what triggered me to make this issue!)

Great :)

**Comment by tjvr** [comment]
I now [have control of moo](https://www.npmjs.com/~tjvr), so we should publish a 1.0.0 soon-ish. A good time to do this would be when we've finalised the API...

@nathan Let me know when you think we're ready to do this. :)

**Comment by nathan** [comment]
> Let me know when you think we're ready to do this. :)

I don't think we're quite ready for 1.0.0 since we're, ahem,

> [changing the API every day](https://semver.org)

**Comment by tjvr** [comment]
> I don't think we're quite ready for 1.0.0

Well, yeah. Obviously. :P

NPM support were advising us to release a 1.0.0... but I guess that assumes the package you're taking over actually has any code in it! :-)

**Comment by nathan** [comment]
Ah, I see what you/they mean. But yeah, it's not like a lot of—well, any—people are depending on the current package

**Comment by tjvr** [comment]
Closed by a4d5c32

**Comment by nathan** [comment]
npm readme still says

> *Hold up a second; we haven't published to NPM yet!*

**Comment by tjvr** [comment]
Yes, it does. :P Unfortunately we can't fix that without publishing a new version :(

I probably should have just left the NPM stuff to you... I'm gonna add you to the package

**Comment by nathan** [comment]
No problem, that's what patch versions are for :)

**Comment by tjvr** [comment]
We should probably add some keywords while we're at it...
