### ISSUE TITLE
lexAll(str) should throw

### ISSUE THREAD

**Issue by tjvr** [tjvr/moo#21]
We should explicitly disallow this sort of thing:

```js
lexer.lexAll(' `a${{c: d}}e` ')
```

**Comment by nathan** [comment]
Why?

**Comment by tjvr** [comment]
To make sure people don't do it by mistake?

Alternatively, have it call reset() first. Either way.

**Comment by nathan** [comment]
`lexAll` itself is generally a Bad Thing to use in real code.

**Comment by tjvr** [comment]
> lexAll itself is generally a Bad Thing to use in real code.

Eh, yeah. True.
