### ISSUE TITLE
Consider ignoring tokens

### ISSUE THREAD

**Issue by tjvr** [tjvr/moo#24]
I have mixed feelings about this sort of thing. It seems reasonable to add `{ignore: true}` for skipping whitespace; but this complicates the implementation of `lex()`, and invites adding more features—like custom transformers that can return multiple tokens, which we then queue up and return on successive `lex()` calls. The latter might be useful, e.g. for tokenizing Python-style indentation; but if we start down this path the lexer might end up more complicated than we want. It would be reasonable to expect users to handle this sort of thing in their own code; for example, as a wrapper around `lex()`.

Thoughts?

**Comment by nathan** [comment]
Perhaps the Right Thing is to make the Lexer [iterable](https://tc39.github.io/ecma262/#sec-iterable-interface), so people can just:

```js
const lexer = moo.compile({
  word: /\w+/,
  ws: {match: /\s+/, lineBreaks: true},
})

lexer.reset(`
 what
  a
   lovely
    example!`)

const tokens = itt(lexer).filter(t => t.type !== 'ws')

// or if you need something more complicated

function* lookahead(it) {
  if (it[Symbol.iterator]) it = it[Symbol.iterator]()
  let {value: prev, done} = it.next(), value
  if (done) return
  while (({value, done} = it.next()) && !done) {
    yield [prev, value]
    prev = value
  }
  yield [prev, null]
}

for (const [here, next] of lookahead(lexer)) {
  // do your thing
}
```

**Comment by tjvr** [comment]
I confess I was unaware of `itt`. Seems neat :D

**Comment by nathan** [comment]
I'm rather fond of iterators :D

**Comment by tjvr** [comment]
> I'm rather fond of iterators :D

I wouldn't have guessed! :P
