### ISSUE TITLE
Refactor to use `type` instead of `name` internally

### ISSUE THREAD

**Issue by nathan** [tjvr/moo#28]
It's somewhat confusing that token types are called `name`s until they are emitted, so we should probably refer to them everywhere as `type`s.

Tim has a bunch of cool PRs in the works right now that touch that code, though, so let's wait until those are merged.

**Comment by tjvr** [comment]
We should do this right after #25.

**Comment by tjvr** [comment]
FWIW, the reason I didn't do this is it seemed nicer to call a rule/group by its "name" than by its "type.

**Comment by nathan** [comment]
That is a good point. I suppose you could call it `tokenType`?
