### ISSUE TITLE
How to distinguish between keywords and identifiers?

### ISSUE THREAD

**Issue by bd82** [tjvr/moo#3]
The order of the RegExp patterns matters.

Lets assume we have two kinds of tokens.
**"or"** keyword token and a general identifier (/[A-Za-z]w+/) token.

- If I place the **"or"** regExp before the identifier regExp than the **identifier** "orly" would be lexed as two **separate** tokens (["or", "ly"].

- If i place the **identifer** regExp before the **"or"** regExp than an **"or"** token will never be matched as the string 'or' also matches an identifier.

**Comment by tjvr** [comment]
> The order of the RegExp patterns matters.

Yes, this is explained in the README. Just make sure the keywords occur first, and everything is fine. :-)

**Comment by tjvr** [comment]
@bd82 Then don't put keywords into the lexer; lex everything as an identifier, and then resolve keywords vs. identifiers after tokenization. :-)
