### ISSUE TITLE
Case insensitive keywords?

### ISSUE THREAD

**Issue by j-s-n** [tjvr/moo#46]
I've got a use case where the keywords in my language are case insensitive but other things (e.g. the contents of strings) aren't. Is there any way I can make a lexer that recognizes these? I tried `keyword: [/foo/i, ...]` but it complains that the "/i" flag isn't allowed.

**Comment by tjvr** [comment]
Right. Moo combines all the tokens into a single RegExp, so supporting both case-sensitive and insensitive tokens is difficult. Can you tell me more about the language? That might help :-)

One suggestion would be to do e.g. `/[fF][oO][oO]/`. You could write a function to generate such RegExps from strings, you needn't do it by hand. :-)

**Comment by j-s-n** [comment]
Ah, yeah. It's a pretty simple DSL where each line starts with a case insensitive keyword, e.g.:
```
enter: (some-terrible-lisp-expression). ;comment
Enter: (another-terrible-lisp-expression).
delete: "string".
```
etc.

I think generating the individual cases won't be too hard, so that will probably work. Thanks.

**Comment by tjvr** [comment]
Glad I could help! :-)

Be aware that you might run into an edge case if you have identifiers too: https://github.com/tjvr/moo#keywords —moo only handles that if your keywords are specified as strings.

**Comment by deltaidea** [comment]
Maybe it would be a good idea to add something like this:
```JS
moo.compile({
  evenOdd: { caseInsensitive: true, keyword: ['even', 'odd'] }
})
```
