### ISSUE TITLE
Order of Rules doesn't seem to work

### ISSUE THREAD

**Issue by techpines** [tjvr/moo#52]
Order of rules seems broken.  I'm using node@6.10.2 and moo@0.3.2.

Specifically, the example in the documentation fails for me:

```js
moo.compile({
    word:  /[a-z]+/,
    foo:   'foo',
}).reset('foo').next() // -> { type: 'word', value: 'foo' }

moo.compile({
    foo:   'foo',
    word:  /[a-z]+/,
}).reset('foo').next() // -> { type: 'foo', value: 'foo' }
```

I am getting `type: foo` for both of these.

**Comment by deltaidea** [comment]
Docs are wrong, actual result is correct. See section [Keywords](https://github.com/tjvr/moo#keywords) of the readme. When a regexp covers a keyword, it's treated as a special case where the keyword always wins. See the link for reasoning.

**Comment by tjvr** [comment]
@deltaidea is right (as usual!). The readme needs updating; it was true when written :-)

**Comment by techpines** [comment]
Is there a way to give a literal precedence? 

```js
moo.compile({
    fortytwo:  /42/,
    identifier:  /[a-z0-9]+/,
}).reset('42abc42')
// -> would like to get ['42', 'abc', '42'] 
// -> instead of ['42', 'abc42']
```

**Comment by nathan** [comment]
> Is there a way to give a literal precedence?

There's always `/(?:(?!42)[a-z0-9])+/`, but that's probably not the best way. It sort of depends on your use case.

**Comment by techpines** [comment]
I am using nearley to parse a markup language, and I am trying to use moo to tokenize for both speed and also to help avoid potential grammar ambiguities.  The main feature in the markup I'm trying to parse are these nested commands with delimiters `{{` and `}}`.  So based on your example, I'm doing this and it works 👍 

```js
/(?:(?!\{\{|\}\})[^])+/
```

But is there a reason why negative lookahead would be bad?

**Comment by deltaidea** [comment]
Another solution is to lex single curly brackets as separate tokens and then deal with combinations in the grammar:

```
command -> %lcurly %lcurly (expression | (%rcurly expression)):* %rcurly %rcurly
```

This rule allows `{{ ... }}` which can contain `}` if it's followed by something else (not second `}`).

If you can change the language spec, you can allow only escaped `}` inside the command: `{{ \} }}`

**Comment by tjvr** [comment]
What is your use case? :-)

Lexers usually try to adhere to the principle of *longest match* (return the longest token possible), since that's usually what you want.

**Comment by techpines** [comment]
I'm trying to parse a couple million snippets of a markup language that have nested commands that are marked by `{{` and `}}`.  And honestly using negative lookahead regex statements seem to be working really well for my use case and the speed seems good.  So I really appreciate everyone's help!

@tjvr I would say, that you've built a really good lexer for Node, and it's unfortunate that users might be turned off because some doc examples are inaccurate. I would be more than happy to submit a PR for some of the doc examples if you need ;) 

The other main doc thing that was bugging me was this in the keywords section you have some syntax errors (unless there are new ES6/7 features I don't know about):
```js
 moo.compile({
      ['lparen',  '('],
      ['rparen',  ')'],
      ['keyword', ['while', 'if', 'else', 'moo', 'cows']],
    })
```

**Comment by tjvr** [comment]
> I would be more than happy to submit a PR for some of the doc examples if you need ;)

That would be lovely, yes please!

> you seem to have some syntax errors

I'm not sure I see what the problem is? :-)

**Comment by nathan** [comment]
> I'm not sure I see what the problem is? :-)

```js
moo.compile({
            ^
  ['lparen',  '('],
  ['rparen',  ')'],
  ['keyword', ['while', 'if', 'else', 'moo', 'cows']],
})
^ 
```

**Comment by tjvr** [comment]
...that took me a while. Thanks, @nathan :-)

**Comment by tjvr** [comment]
Readme updated. Thanks everyone :-)
