### ISSUE TITLE
Keywords design

### ISSUE THREAD

**Issue by tjvr** [tjvr/moo#53]
* Consider making keywords explicit, rather than implicit. Currently it's not obvious that the keyword transform is happening!
* Consider adding an `ignoreCase` option, which is currently missing from Moo (see #46). Note that this can only apply to keyword literals, not RegExps; we can't compile arbitrary regexps to their case-insensitive equivalents! The `value` of the emitted token would always be the originally specified literal (i.e. case-normalised). 
* Allow renaming token types based on their keyword—this would allow writing parsers which switch only on the `type` of tokens, not their value
* Optimise recognition of keywords ([generate a `switch`](http://marijnhaverbeke.nl/blog/acorn.html), rather than using a dict)

**Comment by tjvr** [comment]
Specifying keywords should probably look like this, to match the `{ tokenType: matchPattern }` convention moo uses for specifying lexers.

```js
{
    'kw-while': 'while',
    'kw-else': 'else',
}
```
(With an accompanying public helper function for generating such dicts, from a naming function and a list of keyword literals.)

**Comment by tjvr** [comment]
@nathan You designed most of the Moo API; do you have any suggestions for this? :-)

**Comment by deltaidea** [comment]
If token types are gonna be renamed, will this impact error messages? E.g. `Expected foo but found bar` in nearley.

**Comment by nathan** [comment]
> we can't compile arbitrary regexps to their case-insensitive equivalents!

Well…

**Comment by tjvr** [comment]
Keywords are now explicit.
