### ISSUE TITLE
What do I do if I have two competing matchers

### ISSUE THREAD

**Issue by juliankrispel** [tjvr/moo#54]
In my case I have two competing matchers:

```
{
  ID: /[\w]+/,
  TEXT: /[\w][.]|[^#\n\r]+/,
}
```

If I have a text like this `Something Hello World`

For the first word `ID` will always win. How would I go about letting the other one win? :D

**Comment by tjvr** [comment]
Hello! Have you tried switching the order of the rules? Moo will try the rules in order.

**Comment by juliankrispel** [comment]
@tjvr yes I have. The problem is I want to mostly keep the order as it is.

**Comment by juliankrispel** [comment]
also @tjvr thanks for getting back to me so quick :+1:

**Comment by juliankrispel** [comment]
I guess I'm just wondering if there's any other thing I can do besides using `states` and rule order for this problem...

**Comment by tjvr** [comment]
@juliankrispel You're welcome :-)

**Comment by tjvr** [comment]
You could always try using negative lookahead—see #52.

**Comment by juliankrispel** [comment]
VERY GOOD POINT thx <3

**Comment by tjvr** [comment]
Glad I could help! :-)
