### ISSUE TITLE
Remove support for capturing groups

### ISSUE THREAD

**Issue by tjvr** [tjvr/moo#58]
Does anyone actually use these?

**Comment by nathan** [comment]
Seems useful for string literals: `/"((?:[^"\\]|\\.)*)"/`

**Comment by tjvr** [comment]
Since strings are usually backslash-escaped, you have to transform their value afterwards anyway.

Capturing groups add a fair amount of complexity to moo, and I’m not convinced they’re worth it.

Perhaps we should support general-purpose transform functions? But that sounds like a performance nightmare.

**Comment by nathan** [comment]
Fair enough; you can always do these transformations after the fact. I vote to remove, then.

**Comment by tjvr** [comment]
Closed via #61.

**Comment by nathan** [comment]
Thank goodness for `push -f`, right? :P

**Comment by tjvr** [comment]
Shush, you. :P

**Comment by eykrehbein** [comment]
@tjvr But how to write an expression like `^(.*?):(\s*)\"(?:\\["\\]|[^\n"\\])*\"` without capture groups?
