### ISSUE TITLE
Sort literals globally

### ISSUE THREAD

**Issue by tjvr** [tjvr/moo#59]
Currently, literals in earlier rules will take precedence over later rules, even if they're a prefix.

```
  test('prioritises literals correctly', () => {
    let lexer = moo.compile({
      one: 'moo',
      two: 'moomintroll',
    })
    lexer.reset('moomintroll')
    expect(lexer.next()).toMatchObject({type: 'two'}) // fails
  })
```

This is probably not what we want. We're already special-casing literals; it might not unreasonable to special-case 'em further? Then again, magic is bad. Argh.

**Comment by nathan** [comment]
This seems like the correct behavior. If you replaced them with `/moo/` and `/moomintroll/` you'd get the same result, which is good.

**Comment by tjvr** [comment]
I take it “this” refers to the existing behaviour? So you’d vote to close this?

**Comment by nathan** [comment]
Correct.

**Comment by tjvr** [comment]
Closing; "works as intended".

**Comment by tjvr** [comment]
084b235 adds a test for the current behaviour.
