### ISSUE TITLE
Use case for states

### ISSUE THREAD

**Issue by nathan** [tjvr/moo#6]
String interpolation. It's hard to tokenize this otherwise:

```js
a.b(`c \` ${d.e(`f`, g => {})} h \x0a`)
```

It's also nice to let states inherit rules from other states and be able to count things, e.g. the interpolated expression state needs a `}` rule that can tell if it's a closing brace or the end of the interpolation, but is otherwise identical to the normal expression state.

**Comment by Hardmath123** [comment]
Also, I think nested OCaml or Haskell comments might need states if you want to handle the nesting at the lexer level.

**Comment by nathan** [comment]
> handle the nesting at the lexer level.

I think that requires counting more than states, unless you want an indefinite number of states.

**Comment by Hardmath123** [comment]
Oh, interesting. I guess you can do nested string interpolation because you always escape to the opposite state.

    `abcdef ${12 + `   ${10e10}   ` + 34} ghijkl`
     -------  ***** ---  ***** --- ***** -------

With comments (and possibly with something with three kinds of states?) this wouldn't work. Yikes.

I guess adding a _stack_ would be too much, Tim? :P

**Comment by nathan** [comment]
> you always escape to the opposite state.

Not exactly—consider

```js
`a${{c: d}}e`
--- *****??--
```

You have to have some way of differentiating between closing braces and the end of `${…}`.

> I guess adding a stack would be too much, Tim? :P

I think pushing/popping of states is the right way to handle this sort of thing. Perhaps:

```
moo.states({
  main: {
    str: {match: '`', push: 'lit'},
    ident: /\w+/,
    lbrace: {match: '{', push: 'main'},
    rbrace: {match: '}', pop: 1},
  },
  lit: {
    interp: {match: '${', push: 'main'},
    escape: /\\./,
    end: {match: '`', pop: 1},
    const: /(?:[^$]|\$(?!\{))+/,
  },
})
```

**Comment by tjvr** [comment]
> pushing/popping of states is the right way to handle this sort of thing

That's how most other tokenizers seem to do things.

**Comment by tjvr** [comment]
> `moo.states`

Interesting!

How would you handle sharing tokens between states?

**Comment by nathan** [comment]
> How would you handle sharing tokens between states?

You can let the user do it herself with `Object.assign`, or you can do something slightly horrible like `{ start: {…}, other: {_extend: 'start', …} }`.
