### ISSUE TITLE
Numeric pop

### ISSUE THREAD

**Issue by tjvr** [tjvr/moo#65]
...I was convinced that you could pop multiple states, but that [doesn't appear](https://github.com/tjvr/moo/blob/master/moo.js#L389) to currently be the case.

```js
{match: 'foo', pop: 2}
```

Is this useful, or should I amend the documentation to make clear you can't?

**Comment by nathan** [comment]
I was initially going to allow this, but I couldn't think of any reasonable use cases.

**Comment by nathan** [comment]
Perhaps only disallow numbers that aren't `1`? Some people like to use `{flag: 1}` in object literals because it's short and truthy.

**Comment by tjvr** [comment]
Okay! 7641fd1
