### ISSUE TITLE
Multiple Lexers from the same factory can't be interleaved

### ISSUE THREAD

**Issue by nathan** [tjvr/moo#8]
e.g.:

```js
const factory = moo([['a', 'a'], ['b', 'b']])

const l1 = factory('ab')
const l2 = factory('ab')

l1.lex() // a
l2.lex() // b, should be a
```

**Comment by tjvr** [comment]
Right. You have to explicitly clone() them.

This is why I want to drop the whole "factory" thing—see #4

**Comment by nathan** [comment]
Wouldn't it be easier to have Lexer just always clone the `re` input to its constructor?

**Comment by tjvr** [comment]
@nathan that causes the RegExp to be re-compiled, which is surprisingly expensive. If you're never tokenising more than one thing at once, you want to avoid that cost.

**Comment by nathan** [comment]
I'm aware. That's what the `reset()` method is for, no?

**Comment by nathan** [comment]
I'm aware. The current behavior is very unexpected, though, from the user's perspective.

**Comment by tjvr** [comment]
> I believe setting lastIndex is cheap

I think I measured it to have a slight cost? But you're right, I should fix this. :-)

Regardless, I'm still not sure what the motivation for factory() is.

**Comment by nathan** [comment]
> I think I measured it to have a slight cost?

I said "cheap", not "free" :)

> Regardless, I'm still not sure what the motivation for factory() is.

Agreed. It seems like since the fastest thing to do is use a single Lexer and keep resetting it, the API should probably reflect that. Perhaps add `reset(input)` (or `init`, I'm not sure what to call it), which would do essentially the same thing as `rewind(0); feed(input)` but without the slicing/concatenation.

```js
const lexer = moo({
  ws:      /[ \t]+/,
  rparen:  ')',
  keyword: ['while', 'if', 'else', 'moo', 'cows'],
  NL:      /\n/,
])

lexer.reset('while (10) cows\nmoo')
lexer.lex() // -> { name: 'keyword', value: 'while' }

lexer.reset('if (0) cats\ncattle')
lexer.lex() // -> { name: 'keyword', value: 'if'}
```

**Comment by tjvr** [comment]
> Perhaps add reset(input)

My thoughts exactly! :-)

I think I'm gonna rename it `moo.compile`, to make clear that building a lexer this way is expensive (I don't want users to be calling moo() every time they want to parse something).
